config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
#ゲストログイン機能
  post '/homes/guest_sign_in', to: 'top#new_guest'

  root to: 'top#index' 
  post "income_values/new(/:name)" => "income_values#new"
  post "fixedcost_values/new(/:name)" => "fixedcost_values#new"
  post "variablecost_values/new(/:name)" => "variablecost_values#new"
  
  get "balance_confirm" => "balance_confirm#top"
  post "balance_confirm/show(/:name)" => "balance_confirm#show"
  post "blance_confirm/show_year(/:name)" => "balance_confirm#show_year"
  
  resources :incomes
  resources :fixedcosts
  resources :variablecosts
  resources :income_values
  resources :fixedcost_values
  resources :variablecost_values
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fixedcost.rb
class Fixedcost < ApplicationRecord
  has_many :fixedcost_values, dependent: :destroy
end

app/models/fixedcost_value.rb
class FixedcostValue < ApplicationRecord
end

app/models/income.rb
class Income < ApplicationRecord
  has_many :income_values, dependent: :destroy
end

app/models/income_value.rb
class IncomeValue < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    def self.guest
    user = User.find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      end
    end
end

app/models/variablecost.rb
class Variablecost < ApplicationRecord
  has_many :variablecost_values, dependent: :destroy
end

app/models/variablecost_value.rb
class VariablecostValue < ApplicationRecord
  # validates :save , presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def check_guest
    email = resource&.email || params[:user][:email].downcase
    if email == 'guest@example.com'
      redirect_to root_path, alert: 'ゲストユーザーの編集・削除できません。'
    end
  end

end

app/controllers/fixedcosts_controller.rb
class FixedcostsController < ApplicationController
  def index
    @fixedcosts = Fixedcost.order(created_at: :asc)
  end

  def show
    @fixedcost = Fixedcost.find(params[:id])
  end

  def new
    @fixedcost = Fixedcost.new()
  end
  

  def edit
    @fixedcost = Fixedcost.find(params[:id])
  end

  def create
    Fixedcost.create(fixedcost_params)
    redirect_to root_path, notice: "固定費科目を登録しました"
    # if @fixedcost.save
    #   redirect_to @fixedcost, notice: "固定費科目を登録しました"
    # else
    #   render "new"
    # end
  end

  def update
    @fixedcost = Fixedcost.find(params[:id])
    @fixedcost.update(fixedcost_params)
    # @fixedcost.assign_attributes(params[:fixedcost])
    if @fixedcost.save
      redirect_to @fixedcost, notice: "固定費科目を登録しました"
    else
      render "new"
    end
  end

  def destroy
    @fixedcost = Fixedcost.find(params[:id])
    @fixedcost.destroy
    redirect_to root_path, notice: "固定費科目を削除しました"
  end

  private

  def fixedcost_params
    params.require(:fixedcost).permit(:name,:description)
  end

end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  def index
    @incomes = Income.order(created_at: :asc)
  end

  def show
    @income = Income.find(params[:id])
  end

  def new
    @income = Income.new()
  end

  def edit
    @income = Income.find(params[:id])
  end

  def create
    Income.create(income_params)
    # redirect_to root_path
    # @income = Income.new(params[:income])
    # if income.save
      redirect_to root_path, notice: "収入科目が登録しました"
    # else
      # render "new"
    # end
  end

  def update
    @income = Income.find(params[:id])
    # @income.assign_attributes(params[:income])
    @income.update(income_params)
    if @income.save
      redirect_to @income, notice: "収入科目が登録しました"
    else
      render "new"
    end
  end

  def destroy
    @income = Income.find(params[:id])
    @income.destroy
    redirect_to :incomes, notice: "科目を削除しました"
  end

  private
  
  def income_params
    params.require(:income).permit(:name, :description)
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end

  def show
    @user = User.find(current_user.id)
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/balance_confirm_helper.rb
module BalanceConfirmHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def bootstrap_devise_error_messages!
    return "" if resource.errors.empty?

    html = ""
    resource.errors.full_messages.each do |error_message|
      html += <<-EOF
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">close</span>
        </button>
        #{error_message}
      </div>
      EOF
    end
    html.html_safe
  end
end

app/helpers/fixedcost_values_helper.rb
module FixedcostValuesHelper
end

app/helpers/fixedcosts_helper.rb
module FixedcostsHelper
end

app/helpers/income_values_helper.rb
module IncomeValuesHelper
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/variablecost_values_helper.rb
module VariablecostValuesHelper
end

app/helpers/variablecosts_helper.rb
module VariablecostsHelper
end

app/views/top/index.html.erb
<%= render 'shared/flash_messages' %>
  <% if user_signed_in? %>
    <div class="container">
      <div class="text-center">
        <div class="col  border border-white" id="dropdownMenuButton">
          <div class="dropdown m-4">
            <button class="btn btn-primary dropdown-toggle" type="button"  data-toggle="dropdown" aria-haspopup="ture" aria-expanded="ture">
              科目設定
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <%= link_to "収入科目設定", :incomes, class: "dropdown-item"%>
              <%= link_to "固定費科目設定", :fixedcosts, class: "dropdown-item" %>
              <%= link_to "変動費科目設定", :variablecosts, class: "dropdown-item" %>
            </div>
          </div>
        </div>   
          <div class="dropdown m-4">
            <button class="btn btn-primary dropdown-toggle" type="button"  data-toggle="dropdown" aria-haspopup="ture" aria-expanded="ture">
              収支登録
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <%= link_to "収入金額登録", :income_values,class: "dropdown-item" %>
              <%= link_to "固定費金額登録", :fixedcost_values,class: "dropdown-item" %>
              <%= link_to "変動費金額登録", :variablecost_values,class: "dropdown-item" %>
            </div>
          </div>  
          <div class="content__bottom">
            <h2>収支確認</h2>
            <ul>
              <li><%= link_to "収支確認画面", balance_confirm_path %></li>
            </ul>
          </div>
        </div>
      </div>
      <% else %>
      ログインしてください
      <% end %>