config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
#ゲストログイン機能
  post '/homes/guest_sign_in', to: 'top#new_guest'

  root to: 'top#index' 
  post "income_values/new(/:name)" => "income_values#new"
  post "fixedcost_values/new(/:name)" => "fixedcost_values#new"
  post "variablecost_values/new(/:name)" => "variablecost_values#new"
  
  get "balance_confirm" => "balance_confirm#top"
  post "balance_confirm/show(/:name)" => "balance_confirm#show"
  post "blance_confirm/show_year(/:name)" => "balance_confirm#show_year"
  
  resources :incomes
  resources :fixedcosts
  resources :variablecosts
  resources :income_values
  resources :fixedcost_values
  resources :variablecost_values
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fixedcost.rb
class Fixedcost < ApplicationRecord
  has_many :fixedcost_values, dependent: :destroy
end

app/models/fixedcost_value.rb
class FixedcostValue < ApplicationRecord
end

app/models/form/income_value.rb
class Form::IncomeValue < IncomeValue
  REGISTRABLE_ATTRIBUTES = %i(income_id year_month value description)
  attr_accessor :income_id
  attr_accessor :year_month
  attr_accessor :value
  attr_accessor :description
  validates :value, presence: true
end

app/models/form/income_values.rb
class Form::IncomeValue < IncomeValue
  REGISTRABLE_ATTRIBUTES = %i(income_id year_month value description)
  attr_accessor :income_id
  attr_accessor :year_month
  attr_accessor :value
  attr_accessor :description
end

app/models/income.rb
class Income < ApplicationRecord
  has_many :income_values, dependent: :destroy
end

app/models/income_value.rb
class IncomeValue < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    def self.guest
    user = User.find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      end
    end
end

app/models/variablecost.rb
class Variablecost < ApplicationRecord
  has_many :variablecost_values, dependent: :destroy
end

app/models/variablecost_value.rb
class VariablecostValue < ApplicationRecord
  # validates :save , presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def check_guest
    email = resource&.email || params[:user][:email].downcase
    if email == 'guest@example.com'
      redirect_to root_path, alert: 'ゲストユーザーの編集・削除できません。'
    end
  end

end

app/controllers/fixedcosts_controller.rb
class FixedcostsController < ApplicationController
  def index
    @fixedcosts = Fixedcost.order(created_at: :asc)
  end

  def show
    @fixedcost = Fixedcost.find(params[:id])
  end

  def new
    @fixedcost = Fixedcost.new()
  end
  

  def edit
    @fixedcost = Fixedcost.find(params[:id])
  end

  def create
    Fixedcost.create(fixedcost_params)
    redirect_to root_path, notice: "固定費科目を登録しました"
    # if @fixedcost.save
    #   redirect_to @fixedcost, notice: "固定費科目を登録しました"
    # else
    #   render "new"
    # end
  end

  def update
    @fixedcost = Fixedcost.find(params[:id])
    @fixedcost.update(fixedcost_params)
    # @fixedcost.assign_attributes(params[:fixedcost])
    if @fixedcost.save
      redirect_to @fixedcost, notice: "固定費科目を登録しました"
    else
      render "new"
    end
  end

  def destroy
    @fixedcost = Fixedcost.find(params[:id])
    @fixedcost.destroy
    redirect_to root_path, notice: "固定費科目を削除しました"
  end

  private

  def fixedcost_params
    params.require(:fixedcost).permit(:name,:description)
  end

end

app/controllers/income_values_controller.rb
class IncomeValuesController < ApplicationController
  def index
    @incomes = Income.order(created_at: :asc)
    @income_values = IncomeValue.order(year_month: :asc)
  end

  def show
    @income_value = income_value(params[:id])
  end

  def new
    # year_month_day = params[:year_month] + "-01"
    # @year_month = year_month_day.to_date
    # binding.pry
    @incomes = Income.order(created_at: :asc)
    @form = Form::IncomeForm.new
  end

  def edit
    @income_value = IncomeValue.find(params[:id])
    @income = Income.find(@income_value.income_id)
  end

  def create
    @form = Form::IncomeForm.new(income_form_params)
    if @form.save
      redirect_to :income_values, notice: "登録しました"
    else
      redirect_to new_income_value_path, notice: "登録に失敗しました"
    end
  end

  def update
    @income_value = IncomeValue.find(params[:id])
    @income_value.assign_attributes(params[:income_value])
    if @income_value.save
      redirect_to :income_values, notice: "情報を更新しました"
    else
      render "edit"
    end
  end

  def destroy
    @income_values = IncomeValue.find(params[:id])
    # binding.pry
    @income_values.destroy
    redirect_to :income_values, notice: "データを削除しました。"
  end

  private
  def income_form_params
    params.require(:form_income_form).permit(income_values_attributes: Form::IncomeValue::REGISTRABLE_ATTRIBUTES)
  end
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  def index
    @incomes = Income.order(created_at: :asc)
  end

  def show
    @income = Income.find(params[:id])
  end

  def new
    @income = Income.new()
  end

  def edit
    @income = Income.find(params[:id])
  end

  def create
    Income.create(income_params)
    # redirect_to root_path
    # @income = Income.new(params[:income])
    # if income.save
      redirect_to root_path, notice: "収入科目が登録しました"
    # else
      # render "new"
    # end
  end

  def update
    @income = Income.find(params[:id])
    # @income.assign_attributes(params[:income])
    @income.update(income_params)
    if @income.save
      redirect_to @income, notice: "収入科目が登録しました"
    else
      render "new"
    end
  end

  def destroy
    @income = Income.find(params[:id])
    @income.destroy
    redirect_to :incomes, notice: "科目を削除しました"
  end

  private
  
  def income_params
    params.require(:income).permit(:name, :description)
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end

  def show
    @user = User.find(current_user.id)
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/balance_confirm_helper.rb
module BalanceConfirmHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def bootstrap_devise_error_messages!
    return "" if resource.errors.empty?

    html = ""
    resource.errors.full_messages.each do |error_message|
      html += <<-EOF
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">close</span>
        </button>
        #{error_message}
      </div>
      EOF
    end
    html.html_safe
  end
end

app/helpers/fixedcost_values_helper.rb
module FixedcostValuesHelper
end

app/helpers/fixedcosts_helper.rb
module FixedcostsHelper
end

app/helpers/income_values_helper.rb
module IncomeValuesHelper
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/variablecost_values_helper.rb
module VariablecostValuesHelper
end

app/helpers/variablecosts_helper.rb
module VariablecostsHelper
end

app/views/income_values/edit.html.erb
<h2>収支科目　データ修正 </h2>
  <%= form_for @income_value do |form| %>
  <table>
    <tr>
      <th>登録日</th>
      <th>名称</th>
      <th>値</th>
      <th>備考</th>
    </tr>

  <tr>
    <td><%= form.date_select :year_month,
            start_year: 2010, end_year: Time.current.year,
            use_month_numbers: true, discard_day: true %></td>
    <th><%= @income.name %></th>
    <td><%= form.text_field :value %></td>
    <td><%= form.text_field :description %></td>
  </tr>
  </table>
  <div><%= form.submit %></div>
  <% end %>

app/views/income_values/edti.html.erb
<h2>収支科目　データ修正 </h2>
  <%= form_for @income_value do |form| %>
  <table>
    <tr>
      <th>登録日</th>
      <th>名称</th>
      <th>値</th>
      <th>備考</th>
    </tr>

  <tr>
    <td><%= form.date_select :year_month,
            start_year: 2010, end_year: Time.current.year,
            use_month_numbers: true, discard_day: true %></td>
    <th><%= @income.name %></th>
    <td><%= form.text_field :value %></td>
    <td><%= form.text_field :description %></td>
  </tr>
  </table>
  <div><%= form.submit %></div>
  <% end %>

app/views/income_values/index.html.erb
<% require "active_support/core_ext/numeric/conversions" %>
<h2>収入科目の新規データ登録</h2>
<p>登録年月を設定して下さい</p>
<%= form_tag({controller: :income_values, action: :new}, {method: :post}) do %>
  <input type="month" name="year_month">
  <input type="submit">
<% end %>

<h2>収入科目 データ一覧</h2>
<% if @income_values.present? %>
<table>
  <tr>
    <th>登録年月</th>
    <th>名称</th>
    <th>値</th>
    <th>備考</th>
    <th>操作</th>
  </tr>
  <% @income_values.each do |income_value|%>
  <tr>
    <td><%= income_value.year_month.strftime('%Y年%m月')%></td>
    <td><%= @incomes.find(income_value.income_id).name %></td>
    <td><%= income_value.value.to_s(:delimited) %>円</td>
    <td><%= income_value.description %></td>
    <td>
      <%= link_to "編集", [:edit, income_value]%>
      <%= link_to "削除", income_value, method: :delete, data: { confirm: "本当に削除しますか？"} %>
    </td>
  </tr>
  <% end %>
</table>
<% else %>
  <p>登録されているデータがありません。</p>
<% end %>

app/views/income_values/new.html.erb
<% @page_title = "収入科目 データ登録" %>
<h2><%= @page_title %></h2>
<div class="toolbar"><%= link_to "収入科目データ一覧に戻る", :income_values %></div>
<%= form_for(@form, url: income_values_path, method: :post) do |fb| %>

<!--年月テーブル-->
<table>
  <tr>
    <th>登録年月</th>
    <th>名称</th>
    <th>値</th>
    <th>備考</th>
  </tr>

  <% cnt=0 %>
  <%= fb.fields_for :income_values do |f| %>
  <%= f.hidden_field :income_id %>
    <tr>
        <td>
        <%= f.date_select :year_month,
          start_year: 2010, end_year: Time.current.year,
          use_month_numbers: true, discard_day: true, default: @year_month %>
        </td>
      <th>
        <%= @incomes.find(@form.income_values[cnt].income_id).name %>
      </th>
      <% cnt+=1 %>
      <td><%= f.text_field :value, size: 8 %></td>
      <td><%= f.text_field :description, size: 8 %></td>
    </tr>
  <% end %>
</table>

<div><%= fb.submit %></div>
<% end %>

app/views/income_values/show.html.erb
<h1>show</h1>